---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: ssh-debian12
    image: geerlingguy/docker-debian12-ansible:bookworm
    pre_build_image: true
    privileged: true
    cgroupns_mode: host
    command: /sbin/init
    tmpfs:
      - /run
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw

provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "${MOLECULE_PROJECT_DIRECTORY}/roles"
  config_options:
    defaults:
      remote_tmp: /tmp/.ansible/tmp
  inventory:
    host_vars:
      ssh-debian12:
        ansible_user: root
        ssh:
          port: 2222
          password_auth: "no"
          permit_root_login: "no"
          allow_groups: "ssh-access"
        user:
          admin:
            name: admin
  playbooks:
    converge: converge.yml
    verify: verify.yml

scenario:
  test_sequence:
    - destroy
    - create
    - converge
    - idempotence
    - verify
    - destroy
